In [1]:
from traceback import print_tb

import utils
from copy import deepcopy
import numpy as np
inp = utils.get_input(2025,6,"input")
symbols = inp.pop()
inp = [[int(num) for num in r.split()] for r in inp]
numbers_ = np.array(inp)
symbols_ = np.array(symbols.split())
width = symbols_.size
print(width)

1000


In [6]:
numbers = np.copy(numbers_)
symbols = np.equal(symbols_, np.full(width,'*'))
muls = numbers.prod(axis=0)
adds = numbers.sum(axis=0)
ismuls = np.equal(symbols, np.ones(width))
isadds = np.equal(symbols, np.zeros(width))
total = muls*ismuls + adds*isadds
totalsum = total.sum()

[[   4   82   68 ...    2   84   84]
 [   6   87   39 ...   47   95  519]
 [ 827  446   82 ...   29   27  938]
 [9472  154   36 ...   94   13  354]]
5877594983578


In [3]:
inp=open("input.txt","r").readlines()
import math
nums = []
currnums = []
print(inp)
for x in range(len(inp[0])):
    num =0
    found=False
    for y in range(len(inp)-1):
        print(y)
        char = inp[y][x]
        if char in "0123456789":
            found=True
            num *= 10
            num += int(char)
    if found:
        currnums.append(num)
    else:
        nums.append(currnums)
        currnums=[]
nums.append(currnums)
print(nums)
vals = []
for symbol,num in zip(symbols,nums):
    if symbol == "*":
        vals.append(math.prod(num))
    else:
        vals.append(sum(num))
print(sum(vals))


['   4  82 68 85 74 6  56 14 2  8669 66 13 927  3 235 44   52 16  37  61 82 1774  96 15 775 789 91 374 6579 714 42  269   82 592 53 99 1   6 8   351 553 2122 9  85 8   4   9 98 562  7 8111 3   1958 133 44  458 84 5439 78 96 68 48 242   46 441 42 18 51 31  89 563 5541 964 4393  74 79  26 288 385 11 183 85 94 7439 444 85 587 56 73  9   43 285 242 32   15 247 77   52  75  6  71 75   85 96 143 51  36   1 58 7373 54  3572  5 64 763  76 34 79   43 651 2121 731 3   76  65   372  28 61 8  553 638 472 56 7   25 796  992 356  3 54  7 63   9 192 31 5  2  19 78  183 5868 2762 33   3 516 33  448 7737 99 72 426 96 21 4789 292 69  2  5   324 234  1  699 96 33 676 14 258 63 9342 856 8  994 23 48   4   66   4  6 35  522  74 37  62 831  87 282 139 99  1 55 5  917 5818  3 59  461 4773 78 58  2 98    4 981 468 658 973 6   898   9 165 45 69   85   7 2  69   44 218 21 77  6 989 7  66  7171 663 26 8  9797 85    2 239 92 54 14 7     9 6  116 8827 71 244 276 68  4  95 83 582  44    2  9  698 8236 768 45   197 

In [4]:
import numpy as np
np.set_printoptions(suppress=True)
numbers = np.copy(numbers_)
symbols = np.copy(symbols_)
def tenmul(height, width):
    arr = np.zeros((0, width))   # start 2D
    for _ in range(height):
        arr = arr * 10
        new_row = np.ones((1, width))
        arr = np.vstack([arr, new_row])
    return arr
def exp_adjust(arr):
    h,w = arr.shape
    exps = np.log10(arr+1)
    exps = np.ceil(exps)
    maxexps = np.max(exps,axis=0)
    expdelta =  maxexps - exps
    adjexps = np.power(10,expdelta)
    adjarr = adjexps*arr
    return adjarr


h, w = numbers.shape
mul = tenmul(h, w)

mulnums = np.ones(w)      # shape (w,)
sumnums = np.zeros(w)     # shape (w,)

numbers = exp_adjust(numbers)
print(numbers)

while np.sum(numbers) != 0:
    print()
    digits = np.mod(numbers,10)                 # extract digit
    print(digits)
    col = np.sum(digits*mul, axis=0)
    print(col)
    sumnums += col
    mulnums *= col

    numbers = numbers // 10               # shift to next digit
    numbers = np.floor(numbers)
print()
print(sumnums)
print(mulnums)
print(symbols)
total = mulnums * ismuls + sumnums * isadds


totalsum = np.sum(total)
print(totalsum)


[[4000.  820.   68. ...   20.   84.  840.]
 [6000.  870.   39. ...   47.   95.  519.]
 [8270.  446.   82. ...   29.   27.  938.]
 [9472.  154.   36. ...   94.   13.  354.]]

[[0. 0. 8. ... 0. 4. 0.]
 [0. 0. 9. ... 7. 5. 9.]
 [0. 6. 2. ... 9. 7. 8.]
 [2. 4. 6. ... 4. 3. 4.]]
[   2.   64. 8926. 5226. 4660.  219. 6917. 4920.  868. 9870. 6615. 3919.
 7610.    6. 5200. 4574.  183.  774. 7918.  399. 2581. 4200.  325. 5900.
 5400. 9727. 1518. 4900. 9000. 4919.  167. 9000.   26. 2000. 3136. 9371.
  445.  937.   49. 1960. 3443. 2940.  372. 5800.  917.    5.  464. 8272.
 2000.  139. 1600.  995. 8360. 3718. 4380.   64. 4600. 9940. 8122. 6150.
 8800. 8436. 2159.   16. 1755. 2200. 8567. 1000. 1493.  532. 3380. 1957.
 4600. 3437.   46.  793. 6628. 8770. 5000. 1730. 3747. 5911. 4550. 9700.
 4215. 5152. 7100. 6397. 3920.   51.    1. 5960. 2470.   77. 5110. 7200.
  992.  149.  415.    2.   94.   97. 5437. 6812. 3500.   16. 6960.  823.
 8400. 3000.  317. 2600.   58. 4830.   65. 6213. 4470.  787. 3100. 1

In [5]:
p1,p2=0,0



print("p1",p1)
print("p2",p2)

p1 0
p2 0
